### ISSUE TITLE
이슈(테스크) 카드 체크 리스트

### ISSUE THREAD

**Issue by hankyeolk** [codestates/pily-server#1]
## TODO

클라이언트
- [x]  배포 환경 구축 (CRA, hello world - skeleton 단계) -> AWS S3에 정적 파일 업로드(1차 배포)
- [x]  클라이언트 폴더 구조 (structure) 및 개발 환경 세팅 

- 메인페이지 작업 
  - [x]  개별 매거진 요소 (상세 페이지로 전환 -> 라우팅)
  - [x]  메인페이지 매거진 그리드 (인기/ 최신)
  - [x]  검색 및 알림
  - [x]  로그인, 회원가입 모달을 띄우는 버튼 
  - [x]  페이지네이션 
  - [x]  프로그레스바 (로딩 상태)
  - [x]  픽스된 메뉴 모달 

- 모달
  - [x]  로그인, 회원가입 모달 (소셜 로그인 - 구글, 네이버, 카카오톡)
  - [x]  검색 관련 모달 (검색바, 드롭다운 메뉴)

- 검색
  - [x] 매거진 검색
  - [x] 피드 검색

- 디테일 
  - [x]  디테일한 매거진이 보여지는 뷰
  - [x]  구독 및 좋아요, 유저 디테일 

- 피드 작성 
  - [x]  피드 작성 컴포넌트 구현을 위한 문서 작성 라이브러리 알아보기 
  - [x]  피드 작성 컴포넌트 구현 이슈 생성 및 작업
  - [x]  위치 정보 반영, 별점 시스템 
  - [x]  미리보기 기능 및 미리 보여지는 부분 

- 매거진 작성 
  - [x]  피드의 위치 정보를 어떻게 반영할지 알아보기
  - [x]  매거진 스타일 (가로/세로) 
  - [x]  피드 검색 및 피드 목록 
  - [x]  미리보기

- 마이페이지
  - [x]  마이페이지 전체 설계
  - [x]  유저 정보 관련 
  - [x]  사이드 (메뉴)바 
  - [x]  사이드 메뉴별 뷰 (메뉴별 라우팅에 따른 컴포넌트 구분)
  - [x]  메뉴별 개별 요소

**서버**
- [x] 배포 환경 구축, 배포 skeleton 단계 -> AWS EC2
- [x] 서버 폴더 구조 (structure) 및 개발 환경 세팅 

- 유저 관련 라우팅
   - [x] like, unlike
   - [x] subscribe, unsubscribe
   - [x] get user data,  get Profile

- 인증 (auth)
   - [x] signIn, signOut, signUp
   - [x] social login (OAuth)

- 마이페이지 
   - [x] update profile image, update profile username
   - [x] get (like magazine, subscribe info, my feed, my magazine)

- 작성, 발행, 조회
   - [x] get (megazine, magazine detail)
   - [x] create (feed, magazine)

- DB
   - [x] 시퀄라이즈를 잘 알아보고 스키마 잘 작성하기 
   - [x] 시퀄라이즈 associate를 통한 관계 구성
